name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild -project 'Translator.xcodeproj' -scheme 'Translator' -destination 'platform=IOS Simulator,name=iPhone 8' test
    - name: Build app
      run: xcodebuild -project 'Translator.xcodeproj' -scheme 'Translator' -destination 'generic/platform=IOS' -configuration Release build CODE_SINGNING_ALLOWED=NO
